name: 02 - Eventos
on: 
    push:
    schedule:
        - cron: '43 * * * *'
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: ShowTrigger
              run: echo "ShowTrigger"
